# fly.toml app configuration file generated for mystore12 on 2024-07-18T15:21:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mystore12'
primary_region = 'waw'

[build]
  image = 'miros12/restore:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
